s = set()
# print(type(s))

n = int(input("Enter the 1 numbers: "))
s.add(n)
n = int(input("Enter the 2 numbers: "))
s.add(n)
n = int(input("Enter the 3 numbers: "))
s.add(n)
n = int(input("Enter the 4 numbers: "))
s.add(n)
n = int(input("Enter the 5 numbers: "))
s.add(n)
n = int(input("Enter the 6 numbers: "))
s.add(n)
n = int(input("Enter the 7 numbers: "))
s.add(n)
n = int(input("Enter the 8 numbers: "))
s.add(n)

print(s)